### ISSUE TITLE
web component fails to start

### ISSUE THREAD

**Issue by mbjelac** [EugenMayer/docker-image-concourseci-worker-solid#1]
I just tried `eugenmayer/concourse-worker-solid:3.6.0`. The web component fails to start up. Here are the last few lines from the console before it dies:

```
+ /worker-state/3.6.0/assets/iptables/sbin/iptables -w -N w--input
+ /worker-state/3.6.0/assets/iptables/sbin/iptables -w -F w--input
iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

dns-proxy exited with nil

baggageclaim exited with nil
```

Yes, I tried running it as root. :)

I'm starting it up together with the DB and worker components using `docker-compose` with [this definition](https://gist.github.com/mbjelac/0579875d0c7ff413c14bdabf6d00a0d8).

**Comment by EugenMayer** [comment]
Please also read the docs if you start :)

https://github.com/EugenMayer/docker-image-concourseci-worker-solid

1. remove worker-dir
You basically cannot mount this, since land-worker is not working at all. You can force workder-solid to use land-worker, but it will blow up on boot since still, that is not properly working with concourse-server, there is still a state mixup.

Since we use retire, that state needs to be gone, so remove that volume again
https://gist.github.com/mbjelac/0579875d0c7ff413c14bdabf6d00a0d8#file-docker-compose-yml-L49 rem

You should then also remove https://gist.github.com/mbjelac/0579875d0c7ff413c14bdabf6d00a0d8#file-docker-compose-yml-L58 to keep the state in the default anon volume

2. remove command
https://gist.github.com/mbjelac/0579875d0c7ff413c14bdabf6d00a0d8#file-docker-compose-yml-L46 you can just remove it -basically you did not use the solid implementation yet, since you started the worker directly.

That said, remove this command or use `retire-worker` or `land-worker` as command, to pick the strategy- yet `retire-worker` is the default since `land-worker` cannot be used due to bugs in concourse( also see 1. )

--- 

Just check https://github.com/EugenMayer/concourseci-server-boilerplate - specifically https://github.com/EugenMayer/concourseci-server-boilerplate/blob/master/docker-compose.yml#L49 as a reference

**Comment by mbjelac** [comment]
I'm afraid I cannot keep the state in the default volume, since I have less than 1GB free on that and that space burns up in a matter of seconds when I start up.

I think I'll wait for a non-experimental fix. :)

**Comment by EugenMayer** [comment]
That is not really experimental - what you have right now is experimental :) lets put it that way:

If you have this volume and you do a stack restart ,thing break and whatever is on that volume will not get used - you have to retire the worker manually, then this gets deleted and you start from scratch.

So no matter what you do right now, you end up with a retire and you end up with the state being flushed.

You can put the volume on a name volume still, even if retired, thats not an issue - just know that the content is flushed on a restart.

**Comment by mbjelac** [comment]
I tried to start it up with the empty volume and it uses it, but it still puts stuff in the default volume. Looks like it uses more than the folder I specified in volume mapping.

**Comment by EugenMayer** [comment]
but that has nothing to the with worker-solid - that is not touched at all. I use the concourse/concourse image untouched, adding the script and thats it. So you have there ENV vars and their volume configuration

**Comment by mbjelac** [comment]
Just telling it like it is. :)

Specifics:

- removed the `command: worker` line (46) from the docker-compose file
- deleted the contents of the worker volume
- did `docker-compose up`

I have disk space monitoring on all my logical partitions.

On "old" Concourse startup, the docker partition goes up by a few MB, and the worker partition goes up by about 1GB.

With this setup, the docker partition also goes up by about 1GB (or tries to, but doesn't have enough space).

Could you advise on what other folders in the worker container I could map to the external volume?

**Comment by EugenMayer** [comment]
This is a question for concourse/concourse rather then this issue itself i would guess
